name = "Airtable"
uuid = "96f7d883-6668-4fbe-bb01-b60427b16035"
authors = ["Kevin Bonham PhD <kevbonham@gmail.com>", "contributors"]
version = "0.1.1"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
HTTP = "0.8, 0.9"
JSON3 = "1"
julia = "1.5"
